---
dist: trusty
language: php

matrix:
  include:
    # Legacy factories requires ^7.3|^8.0
    # - php: 7.2
    #   env: ILLUMINATE=^6
    # - php: 7.2.5
    #   env: ILLUMINATE=^7
    - php: 7.3
      env: ILLUMINATE=^6
    - php: 7.3
      env: ILLUMINATE=^7
    - php: 7.3
      env: ILLUMINATE=^8
    - php: 7.4
      env: ILLUMINATE=^6
    - php: 7.4
      env: ILLUMINATE=^7
    - php: 7.4
      env: ILLUMINATE=^8

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer require "illuminate/database:${ILLUMINATE}" --no-update
  - composer require "illuminate/support:${ILLUMINATE}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
